/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.pa.exam.app;

import it.unicam.pa.exam.api.CoordinateInterface;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class CoordinateTest {
    @Test
    void testConstructor() {
        CoordinateInterface c = new SquareCoordinate(10, 20, 300);
        assertEquals(10, c.getX());
        assertEquals(20, c.getY());
        CoordinateInterface co = new Coordinate(10, 20, 300, 200);
        assertEquals(10, c.getX());
        assertEquals(20, c.getY());
    }

    @Test
    void testSet() {
        CoordinateInterface c = new Coordinate(10, 20, 50, 60);
        c.setNewPosition(30, 40);

        assertEquals(30, c.getX());
        assertEquals(40, c.getY());

        c.setNewPosition(50, 60);

        assertThrows(IllegalArgumentException.class, () -> c.setNewPosition(100, 40));
        assertThrows(IllegalArgumentException.class, () -> c.setNewPosition(10, 90));
        assertThrows(IllegalArgumentException.class, () -> c.setNewPosition(-1, 30));
        assertThrows(IllegalArgumentException.class, () -> c.setNewPosition(10, -90));
    }

    @Test
    void testGetArray() {
        CoordinateInterface c = new Coordinate(2, 4, 10, 20);

        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 20; j++) {
                c.setNewPosition(i, j);
                assertEquals(c.getPositionAsArray()[0], c.getX());
                assertEquals(i, c.getX());

                assertEquals(c.getPositionAsArray()[1], c.getY());
                assertEquals(j, c.getY());
            }
        }
    }
    @Test
    void testGetMax(){
        CoordinateInterface c = new SquareCoordinate(0,0,250);

    }
}
