/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.pa.exam.app.Module;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class LimitedPointTest {
    @Test
    void testConstructor() {
        LimitedPoint c = new SquareLimitedPoint(10, 20, 300);
        assertEquals(10, c.getX());
        assertEquals(20, c.getY());
        LimitedPoint co = new LimitedPoint(10, 20, 300, 200);
        assertEquals(10, c.getX());
        assertEquals(20, c.getY());
    }

    @Test
    void testSet() {
        LimitedPoint c = new LimitedPoint(10, 20, 50, 60);
        c.setLocation(30, 40);

        assertEquals(30, c.getX());
        assertEquals(40, c.getY());

        c.setLocation(100, 40);
        assertEquals(c.getHeight(),c.getX());

        c.setLocation(10, 1280);
        assertEquals(c.getWidth(),c.getY());
    }

    @Test
    void testGetArray() {
        LimitedPoint c = new LimitedPoint(2, 4, 10, 20);

        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 20; j++) {
                c.setLocation(i, j);
                assertEquals(c.getLocation().getX(), c.getX());
                assertEquals(i, c.getX());

                assertEquals(c.getLocation().getY(), c.getY());
                assertEquals(j, c.getY());
            }
        }
    }
    @Test
    void testGetMax(){
        LimitedPoint c = new SquareLimitedPoint(0,0,250);

    }
}
