/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.pa.exam.api.Model;

import it.unicam.pa.exam.api.Model.Logo.LimitedPoint;
import it.unicam.pa.exam.api.Model.Logo.SquareLimitedPoint;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class LimitedPointTest {
    @Test
    void testConstructor() {
        LimitedPoint c = new SquareLimitedPoint(10, 20, 300);
        assertEquals(10, c.getX());
        assertEquals(20, c.getY());

        c = new LimitedPoint(10, 20, 200, 300);
        assertEquals(10, c.getX());
        assertEquals(20, c.getY());

        c = new LimitedPoint(10, 20, 5, 15);
        assertEquals(5, c.getX());
        assertEquals(15, c.getY());

        c.setLocation(new LimitedPoint(10, 5, 10, 10));

    }

    @Test
    void testSet() {
        LimitedPoint c = new LimitedPoint(10, 20, 40, 60);
        c.setLocation(30, 40);

        assertEquals(30, c.getX());
        assertEquals(40, c.getY());

        c.setLocation(100, 40);
        assertEquals(c.getWidth(), c.getX());

        c.setLocation(10, 1280);
        assertEquals(c.getHeight(), c.getY());
    }

    @Test
    void testGetArray() {
        LimitedPoint c = new LimitedPoint(2, 4, 10, 20);

        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 20; j++) {
                c.setLocation(i, j);
                assertEquals(c.getLocation().getX(), c.getX());
                assertEquals(i, c.getX());

                assertEquals(c.getLocation().getY(), c.getY());
                assertEquals(j, c.getY());
            }
        }
    }

    @Test
    void testGetMax() {
        LimitedPoint c = new SquareLimitedPoint(0, 0, 250);

    }
}
