/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.pa.exam.utilities;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
    //todo remove this before build
}
